# Generated by Django 4.0.4 on 2022-04-27 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=250, verbose_name='Название категории')),
                ('category_slug', models.SlugField(max_length=250, verbose_name='Слаг поле категории')),
            ],
            options={
                'verbose_name_plural': 'Категории',
                'db_table': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_name', models.CharField(max_length=250, verbose_name='Название марки')),
                ('mark_slug', models.SlugField(max_length=255, verbose_name='Слаг поле марки')),
                ('image', models.ImageField(blank=True, upload_to='images/shop')),
            ],
            options={
                'verbose_name_plural': 'Марки',
                'db_table': 'Марка',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=255, verbose_name='Оригинальный артикул')),
                ('article_second', models.CharField(max_length=255, verbose_name='Дополнительный артикул')),
                ('part_name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('part_exist', models.BooleanField(verbose_name='Наличие')),
                ('part_slug', models.SlugField(max_length=250, verbose_name='Слаг')),
                ('part_price', models.IntegerField(verbose_name='Цена запчасти')),
                ('image', models.ImageField(upload_to='images/shop')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name_plural': 'Детали',
                'db_table': 'Деталь',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255, verbose_name='Название модели')),
                ('model_slug', models.SlugField(max_length=255, verbose_name='Слаг поле модели')),
                ('image', models.ImageField(upload_to='images/shop')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark', to='catalog.mark', verbose_name='Марка')),
            ],
            options={
                'verbose_name_plural': 'Модели',
                'db_table': 'Модель',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model', to='catalog.model', verbose_name='Модель'),
        ),
    ]
