# Generated by Django 4.0.4 on 2022-05-11 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=250, verbose_name='Имя для категории')),
                ('list_slug', models.SlugField(max_length=255, unique=True, verbose_name='slug для категории')),
                ('image', models.ImageField(blank=True, upload_to='images/shop')),
            ],
            options={
                'verbose_name_plural': 'Категории запчастей',
                'db_table': 'Категория запчасти',
            },
        ),
        migrations.RemoveField(
            model_name='model',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='category',
            name='model',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/shop'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=250, verbose_name='Название подкатегории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(max_length=250, verbose_name='slug поле подкатегории'),
        ),
        migrations.DeleteModel(
            name='Mark',
        ),
        migrations.DeleteModel(
            name='Model',
        ),
        migrations.AddField(
            model_name='category',
            name='part_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='catalog.partlist', verbose_name='подкатегория'),
        ),
    ]
