# Generated by Django 4.0.4 on 2022-04-29 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_partlist_remove_model_mark_remove_category_model_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partlist',
            old_name='mark_slug',
            new_name='list_slug',
        ),
    ]
