# Generated by Django 4.0.4 on 2022-05-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_partlist_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partlist',
            name='mark',
            field=models.CharField(max_length=250, verbose_name='Марка'),
        ),
    ]
