# Generated by Django 4.0.4 on 2022-05-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_partlist_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название марки')),
                ('image', models.ImageField(upload_to='images/mark', verbose_name='Картинка')),
            ],
        ),
    ]
