# Generated by Django 4.0.4 on 2022-05-12 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_mark'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Part',
            new_name='Product',
        ),
        migrations.AlterModelOptions(
            name='mark',
            options={'verbose_name_plural': 'Марки'},
        ),
    ]
