# Generated by Django 4.0.4 on 2022-05-01 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_part_parts_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='parts_list',
        ),
    ]
