# Generated by Django 4.0.4 on 2022-05-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_rename_part_product_alter_mark_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='part_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='part_price',
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
