# Generated by Django 4.0.4 on 2022-05-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_part_parts_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(max_length=250, unique=True, verbose_name='slug поле подкатегории'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_slug',
            field=models.SlugField(max_length=250, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='partlist',
            name='list_slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='slug для категории'),
        ),
    ]
