# Generated by Django 4.0.4 on 2022-05-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_product_part_name_remove_product_part_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parts', models.CharField(max_length=1000, verbose_name='Запчасти')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=15)),
                ('address', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=200, verbose_name='Пользователь')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
