# Generated by Django 4.0.4 on 2022-05-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_category_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='part_slug',
            field=models.SlugField(max_length=250, verbose_name='Слаг'),
        ),
    ]
