# Generated by Django 4.0.4 on 2022-05-20 21:51

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_order_alter_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='order',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='order',
            name='orient',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ориентир'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Адресс'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Общая цена'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Пользователь'),
        ),
        migrations.AlterModelTable(
            name='order',
            table='Заказ',
        ),
    ]
