# Generated by Django 4.0.4 on 2022-05-26 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_part_part_slug'),
        ('catalog', '0010_alter_order_user'),
    ]

    operations = [
    ]
